version: '3'
services:
  recatch:
    image: recatch:latest
    container_name: recatch
    ports:
      - "8084:8084"
    environment:
      - PROXY_PORT=8082
      - PORT=8084
      - PROXY_HOST=192.168.0.1